### PR TITLE
Migrate to most recent ChakraUI version

### LINKED ISSUE #27: Migrate ChakraUI to v2 for new features
Based on [this ticket](https://github.com/codeday/topo/issues/17), it seems as though we need to migrate ChakraUI to v2 in order to continue adding new elements.

### PR DESCRIPTION
**Pull request by buenobunny**
To solve [this issues](https://github.com/codeday/topo/issues/27), upgraded ChakraUI to newest version to unblock [this ticket](https://github.com/codeday/topo/issues/17). Verified that the topo-docs still work.

### CODE REVIEW

**Comment by buenobunny** [comment]
Just to be clear, I have no clue how this will affect downstream

**Comment by oohwooh** [comment]
This seems to be more involved than initially thought but I'm working on it. We may have to switch docs providers. I'm not concerned with downstream, currently, it would not be the first time we had significant breaking changes from an update.

**Comment by oohwooh** [comment]
I somehow _really_ messed up my dev environment which is what caused the problems I was having. I am testing for any patchable downstream effects then will merge

**Comment by oohwooh** [comment]
things are functional enough downstream, only issue I can immediately notice is deprecation of `d=` but that is a simple find and replace.

**Pull request merged**
